image: node:latest
include:
  template: Jobs/Code-Quality.gitlab-ci.yml

cache:
  paths:
    - node_modules/
stages:
    - test

test:
  before_script:
    - npm install
  script:
    - npm run coverage
  after_script:
    - npm run report-coverage
  coverage:
    /All files[^|]*\|[^|]*\s+([\d\.]+)/

code_quality:
  allow_failure: true
  artifacts:
    paths: [gl-code-quality-report.json]
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
