image: node:latest
include:
  template: Jobs/Code-Quality.gitlab-ci.yml

cache:
  paths:
    - node_modules/
stages:
    - test

test:
  before_script:
    - npm install
  script:
    - npm run coverage
  after_script:
    - npm run report-coverage

code_quality:
  coverage:
    /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths: [gl-code-quality-report.json]
