# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest
include:
  template: Jobs/Code-Quality.gitlab-ci.yml

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
stages:
    - test
    
test:
  before_script:
    - npm install --only=dev
  script:
    - npm run coverage
  after_script:
    - npm run report-coverage
  coverage:
    /All files[^|]*\|[^|]*\s+([\d\.]+)/

code_quality:
  allow_failure: true
  artifacts:
    paths: [gl-code-quality-report.json]
